workspace:
  base: /home/drone-demo
  path: .

kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: 386

steps:
- name: build
  commands:
  - echo hello
  - pwd

trigger:
  branch:
  - master